# GitHub Issue Templates

Create these files in `.github/ISSUE_TEMPLATE/` directory:

## 1. Bug Report Template
**File**: `.github/ISSUE_TEMPLATE/bug_report.yml`

```yaml
name: Bug Report
description: File a bug report to help us improve Ainux OS
title: "[BUG] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out this form completely.

  - type: input
    id: version
    attributes:
      label: Ainux OS Version
      description: What version of Ainux OS are you running?
      placeholder: "v2.1"
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Build System
        - Kernel
        - GPU Drivers
        - NPU Support
        - Cluster Management
        - Installation
        - Boot Process
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is
      placeholder: Describe the issue...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: hardware
    attributes:
      label: Hardware Information
      description: |
        Please run these commands and paste the output:
        ```bash
        lscpu
        lspci | grep -E "(VGA|3D)"
        free -h
        uname -a
        ```
      render: shell
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Any relevant log output
      render: shell

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues
          required: true
        - label: I have included system information
          required: true
        - label: I can reproduce this issue consistently
          required: true
```

## 2. Feature Request Template
**File**: `.github/ISSUE_TEMPLATE/feature_request.yml`

```yaml
name: Feature Request
description: Suggest a new feature for Ainux OS
title: "[FEATURE] "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide details below.

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - Hardware Support
        - AI Framework Integration
        - Cluster Management
        - Performance Optimization
        - User Interface
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I need this feature because...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions?

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation
      options:
        - label: I would be willing to implement this feature
        - label: I can provide testing for this feature
        - label: I can help with documentation
```

## 3. Hardware Support Template
**File**: `.github/ISSUE_TEMPLATE/hardware_support.yml`

```yaml
name: Hardware Support Request
description: Request support for specific hardware
title: "[HARDWARE] "
labels: ["hardware", "enhancement"]
body:
  - type: dropdown
    id: hardware_type
    attributes:
      label: Hardware Type
      options:
        - GPU (NVIDIA)
        - GPU (AMD)
        - GPU (Intel)
        - NPU (Neural Processing Unit)
        - Network Adapter
        - Storage Device
        - Other
    validations:
      required: true

  - type: input
    id: hardware_model
    attributes:
      label: Hardware Model
      description: Exact model name and number
      placeholder: "NVIDIA RTX 4090, AMD RX 7900 XTX, etc."
    validations:
      required: true

  - type: textarea
    id: hardware_specs
    attributes:
      label: Hardware Specifications
      description: |
        Please provide detailed specs:
        ```bash
        lspci -v | grep -A 20 "VGA\|3D\|NPU"
        lsusb
        ```
      render: shell

  - type: textarea
    id: current_status
    attributes:
      label: Current Status
      description: What happens when you try to use this hardware?
      placeholder: "Not detected, partial functionality, etc."

  - type: input
    id: driver_version
    attributes:
      label: Recommended Driver Version
      description: If known, what driver version should be used?
      placeholder: "v560.35, ROCm 6.2, etc."

  - type: checkboxes
    id: testing
    attributes:
      label: Testing Availability
      options:
        - label: I have this hardware available for testing
        - label: I can provide detailed feedback
        - label: I'm willing to test development builds
```

## 4. Pull Request Template
**File**: `.github/PULL_REQUEST_TEMPLATE.md`

```markdown
## Description
Brief description of the changes in this PR.

## Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Performance improvement
- [ ] Code refactoring

## Related Issues
Fixes #(issue number)

## Changes Made
- 
- 
- 

## Testing
### Test Environment
- [ ] Ubuntu 22.04 LTS
- [ ] Hardware: (specify GPU/NPU models tested)
- [ ] Build completed successfully
- [ ] QEMU test passed
- [ ] Hardware validation passed

### Test Results
```bash
# Include output from:
sudo validate-hardware
```

## Screenshots (if applicable)
Add screenshots to help explain your changes.

## Checklist
- [ ] My code follows the project's coding standards
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Additional Notes
Any additional information about this PR.
```
