name: Bug Report
description: File a bug report to help us improve Ainux OS
title: "[BUG] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out this form completely.

  - type: input
    id: version
    attributes:
      label: Ainux OS Version
      description: What version of Ainux OS are you running?
      placeholder: "v2.1"
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Build System
        - Kernel
        - GPU Drivers
        - NPU Support
        - Cluster Management
        - Installation
        - Boot Process
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is
      placeholder: Describe the issue...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: hardware
    attributes:
      label: Hardware Information
      description: |
        Please run these commands and paste the output:
        ```bash
        lscpu
        lspci | grep -E "(VGA|3D)"
        free -h
        uname -a
        ```
      render: shell
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Any relevant log output
      render: shell

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues
          required: true
        - label: I have included system information
          required: true
        - label: I can reproduce this issue consistently
          required: true
